### ISSUE TITLE
Product Details

### ISSUE THREAD

**Issue by jhuang15** [Elizabethccc/SearchParty#10]
--Write down details about the product, purpose, how to us, FAQ, etc.

**Comment by htking1195** [comment]
Users will be able to use the APP to search for online courses, any category.
Search will generate a list displaying all available courses that meets your criteria , paid and free.
A  user account system will be created to allow users to save courses and access at a later time.
A filter will be designed to allow users to further select specific course details such as sub categories , time and date, and course length
