### ISSUE TITLE
Plan out app layout

### ISSUE THREAD

**Issue by jhuang15** [Elizabethccc/SearchParty#13]
--Discuss how the app should look, how many activities, a list, sidebar, menu, etc.

**Comment by Elizabethccc** [comment]
Search category sidebar, should include options to save course in folder, a drop down menu for login/log out, history, saved/favorites folder (or could be a visible icon), and profile info

**Comment by ChrishaunMitchell** [comment]
![app sample general2](https://user-images.githubusercontent.com/49069651/65288028-47faef80-db13-11e9-9a23-5f298cc7bfb8.jpg)

I created a visual on how the layout can look based on the menus needed.
